### ISSUE TITLE
Running this maven plugin twice on XML files adds an extra line

### ISSUE THREAD

**Issue by vmassol** [mycila/license-maven-plugin#37]
Here's an input example:

    <?xml version="1.0" encoding="UTF-8"?>

    <xwikidoc>

After running the plugin once, I get:

    <?xml version="1.0" encoding="UTF-8"?>
    

    <xwikidoc>

And running it again addes an extra new line just after the first line:

    <?xml version="1.0" encoding="UTF-8"?>

    

    <xwikidoc>

It's not normal than running the plugin twice generates a change.

Thanks

**Comment by McFoggy** [comment]
I do not reproduce ; neither in 2.10 or in latest 2.11-SNAPSHOT version.

**Comment by vmassol** [comment]
Just tested and same problem with 2.10

**Comment by vmassol** [comment]
FTR this is how I use it and how I reproduce the problem:

`````
    protected void executeLicenseGoal(String goal) throws MojoExecutionException
    {
        Dependency dep = new Dependency();
        dep.setGroupId("org.xwiki.commons");
        dep.setArtifactId("xwiki-commons-tool-verification-resources");
        dep.setVersion(getXWikiCommonsVersion());

        Plugin licensePlugin = plugin(
            groupId("com.mycila"),
            artifactId("license-maven-plugin"),
            version("2.6"));
        licensePlugin.setDependencies(Collections.singletonList(dep));

        executeMojo(
            licensePlugin,
            goal(goal),
            configuration(
                element(name("header"), "license.txt"),
                element(name("strictCheck"), "true"),
                element(name("headerDefinitions"),
                    element(name("headerDefinition"), "license-xml-definition.xml")),
                element(name("includes"),
                    element(name("include"), "src/main/resources/**/*.xml"))
            ),
            executionEnvironment(
                this.project,
                this.mavenSession,
                this.pluginManager
            )
        );
    }
`````

**Comment by McFoggy** [comment]
What is the content of your specific XML headerDefinition file?
Do you reproduce if you omit your specific definition and use the default one?

**Comment by vmassol** [comment]
my license-xml-definition.xml contains:

`````
<additionalHeaders>
  <xml_style>
    <firstLine><![CDATA[<!--]]></firstLine>
    <beforeEachLine> * </beforeEachLine>
    <endLine><![CDATA[-->]]></endLine>
    <skipLine><![CDATA[^<\?xml.*>$]]></skipLine>
    <firstLineDetectionPattern><![CDATA[(\s|\t)*<!--.*$]]></firstLineDetectionPattern>
    <lastLineDetectionPattern><![CDATA[.*-->(\s|\t)*$]]></lastLineDetectionPattern>
    <allowBlankLines>false</allowBlankLines>
    <isMultiline>true</isMultiline>
  </xml_style>
</additionalHeaders>
`````

**Comment by vmassol** [comment]
"Do you reproduce if you omit your specific definition and use the default one?"

I've just tried it and I get exactly the same problem with the default definition file.

**Comment by McFoggy** [comment]
Can you please checkout the branch in which I pushed a test case and execute it on your environment?

**Comment by vmassol** [comment]
Hi @McFoggy and sorry for not answering faster... I have now cloned https://github.com/McFoggy/license-maven-plugin.git and checked out branc

**Comment by mathieucarbou** [comment]
I franckly don't know... I will update the project to 3.0.rc1 soon with inclusion if some @McFoggy's commits. You can retry after than...

**Comment by mathieucarbou** [comment]
closing due to non updates

**Comment by vmassol** [comment]
FTR the issue is still there and causing problems on the xwiki project where we still have to run this plugin twice everytime in order to get a stable result.

**Comment by vmassol** [comment]
Note that this is what happens:
* First run: license is added (you need to test without any license)
* Second run: the new line is added

**Comment by vmassol** [comment]
I've debugged the problem more and you were right and I deeply apologize: the issue is in our code and not in this plugin's code. Sorry about that.

**Comment by McFoggy** [comment]
Thank you Vincent for the update.
